# Generated by Django 4.1 on 2023-02-14 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CardSectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='dt_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MC_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_question', models.CharField(max_length=500)),
                ('field_answer', models.TextField(blank=True, max_length=1000)),
                ('field_answer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mc_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc_and_datasheet.mc_section')),
            ],
        ),
        migrations.CreateModel(
            name='dt_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_question', models.CharField(max_length=500)),
                ('field_answer', models.TextField(blank=True, max_length=1000)),
                ('field_answer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc_and_datasheet.dt_section')),
            ],
        ),
    ]
