# Generated by Django 4.2.3 on 2023-07-18 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mc_and_datasheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDataDatacard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CardDataDatasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='dc_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='carddata',
            name='carddata_session',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dt_field',
            name='field_helper',
            field=models.CharField(default='Info about the field', max_length=500),
        ),
        migrations.AddField(
            model_name='dt_section',
            name='section_desc',
            field=models.CharField(default='Info about the section', max_length=500),
        ),
        migrations.AddField(
            model_name='field',
            name='field_helper',
            field=models.CharField(blank=True, default='Info about the field', max_length=1000),
        ),
        migrations.AddField(
            model_name='field',
            name='field_session',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='file_session',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_section_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mc_section',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mc_section',
            name='mc_section_session',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mc_section',
            name='section_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.CharField(max_length=50, unique=True)),
                ('input_data', models.JSONField()),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='dc_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_question', models.CharField(max_length=500)),
                ('field_answer', models.TextField(blank=True, max_length=1000)),
                ('field_answer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc_and_datasheet.dt_section')),
            ],
        ),
    ]
