# Generated by Django 4.1.7 on 2023-04-11 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0002_carddatadatasheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDataDatasdsfheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
