# Generated by Django 4.2.3 on 2023-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0002_carddatadatacard_carddatadatasheet_dc_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_session',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mc_section',
            name='mc_section_session',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
