# Generated by Django 4.0.4 on 2023-01-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0003_rename_todolist_item_mc_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_question', models.CharField(max_length=500)),
                ('field_answer', models.CharField(max_length=500)),
                ('complete', models.BooleanField()),
                ('mc_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc_and_datasheet.mc_section')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
