# Generated by Django 4.1.7 on 2023-09-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0003_alter_field_field_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_field',
            name='field_session',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dt_section',
            name='dt_section_session',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
