# Generated by Django 4.1.7 on 2023-04-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0003_carddatadatasdsfheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardDataDatasdsfheet',
        ),
    ]
