# Generated by Django 4.2.1 on 2023-05-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0004_delete_carddatadatasdsfheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_section',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
