# Generated by Django 4.1.7 on 2023-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0004_dt_field_field_session_dt_section_dt_section_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddatadatasheet',
            name='carddata_session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
