# Generated by Django 4.2.1 on 2023-05-16 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0005_mc_section_click_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDataDatacard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='dc_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='dc_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_question', models.CharField(max_length=500)),
                ('field_answer', models.TextField(blank=True, max_length=1000)),
                ('field_answer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc_and_datasheet.dt_section')),
            ],
        ),
    ]
