# Generated by Django 4.2 on 2023-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0006_carddatadatacard_dc_section_dc_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_field',
            name='field_helper',
            field=models.CharField(default='Info about the field', max_length=500),
        ),
        migrations.AddField(
            model_name='field',
            name='field_helper',
            field=models.CharField(default='Info about the field', max_length=500),
        ),
    ]
