# Generated by Django 4.2 on 2023-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0007_dt_field_field_helper_field_field_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_section',
            name='section_desc',
            field=models.CharField(default='Info about the section', max_length=500),
        ),
        migrations.AddField(
            model_name='mc_section',
            name='section_desc',
            field=models.CharField(default='Info about the section', max_length=500),
        ),
    ]
