# Generated by Django 4.2.2 on 2023-06-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0008_dt_section_section_desc_mc_section_section_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_section_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_helper',
            field=models.CharField(blank=True, default='Info about the field', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mc_section',
            name='section_desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
