# Generated by Django 4.2.2 on 2023-07-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mc_and_datasheet', '0009_file_uploaded_section_id_alter_field_field_helper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_section',
            name='mc_section_session',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.CharField(max_length=50, unique=True)),
                ('input_data', models.JSONField()),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
    ]
