# Generated by Django 4.2.2 on 2023-07-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0009_file_uploaded_section_id_alter_field_field_helper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('input_data', models.JSONField()),
            ],
        ),
    ]
