# Generated by Django 4.2.2 on 2023-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0010_mc_section_mc_section_session_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
