# Generated by Django 4.2 on 2023-07-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0011_field_field_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='carddata_session',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='file_session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
