# Generated by Django 4.2 on 2023-07-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0002_carddatadatacard_carddatadatasheet_dc_section_and_more'),
        ('mc_and_datasheet', '0012_carddata_carddata_session_file_file_session'),
        ('mc_and_datasheet', '0014_alter_file_file_session'),
    ]

    operations = [
    ]
