# Generated by Django 4.2 on 2023-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0015_merge_20230703_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_session',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
