# Generated by Django 4.2 on 2023-07-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_and_datasheet', '0016_alter_file_file_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/a/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_session',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
