name: Django Test 

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]
    pull_request:
        branches: [main]

jobs:
  build_and_push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sperbaha/featai:latest

  execute_tests:
    name: Execute tests in Docker
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        uses: docker://sperbaha/featai:latest
        with:
          entrypoint: /bin/bash
          args: -c "cd /home/app/webapp && python manage.py test"